#!/bin/bash

# clone the content from and place correctly in session
git clone https://github.com/fomightez/3Dscatter_plot-binder
rm 3Dscatter_plot-binder/requirements.txt
cp 3Dscatter_plot-binder/*.ipynb .
cp 3Dscatter_plot-binder/*.tsv .
rm -rf 3Dscatter_plot-binder


# clean up / declutter a bit ;
# this will make it easier to see the files
rm -rf 3Dscatter_plot-binder
rm README.md
rm -rf details_on_versions_noted_when_all_working


# fix the links to the direct voila/render launch to use the corresponding environment that the notebooks will also be using
sed -i 's|https://mybinder\.org/v2/gh/fomightez/3Dscatter_plot-binder/HEAD?urlpath=voila%2Frender%2F3D_scatter_Voila_matplotlibSTREAMLINED\.ipynb|https://mybinder.org/v2/gh/fomightez/3Dscatter_plot_mod_playground-binder/HEAD?urlpath=voila%2Frender%2F3D_scatter_Voila_matplotlibSTREAMLINED.ipynb|g' index.ipynb
sed -i 's|https://mybinder\.org/v2/gh/fomightez/3Dscatter_plot-binder/HEAD?urlpath=voila%2Frender%2F3D_scatter_Voila_matplotlibSTREAMLINED\.ipynb|https://mybinder.org/v2/gh/fomightez/3Dscatter_plot_mod_playground-binder/HEAD?urlpath=voila%2Frender%2F3D_scatter_Voila_matplotlibSTREAMLINED.ipynb|g' 3D_scatter_Voila_matplotlibSTREAMLINED.ipynb


# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"